version: '3.7'
services:
    kerberos:
        container_name: kerberos
        ports:
            - '8080:8080'
            - '5900:5900'
            - '6080:6080'
        volumes:
            - type: bind
              source: /ros-persistent-data
              target: /my_ros_data
              volume:
                nocopy: true
            - type: volume
              source: workspace
              target: /workspace
              volume:
                nocopy: true
        image: johannhaselberger/coros
    carla:
        container_name: carla_sim
        image: carlasim/carla:0.9.10
        command: ./CarlaUE4.sh -opengl
        ports:
            - '2000:2000'
            - '2001:2001'
            - '2002:2002'
        environment:
            - SDL_VIDEODRIVER=x11
            - DISPLAY=$DISPLAY
        volume:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu, utility]
volumes:
    workspace:
